### PR TITLE
Tidy shell script

### LINKED ISSUE #4: Add shell script linting for servo-warc-tests.sh
While looking at [this failed run](http://build.servo.org/builders/linux-nightly/builds/586/steps/test/logs/stdio) (via [#servo](https://mozilla.logbot.info/servo/20180129#c14205975)), beyond the fix in #3, it also looks like there are some additional issues with the `servo-warc-tests.sh` shell script. The biggest ones are:

- lack of `set -o errexit` to cause the script to exit on failure instead of continuing (see how the log shows attempted access to `/warc-tests-2018-01-29.csv` and `/ARCHIVES` after the original realpath failure); `set -o nounset` and `set -o pipefail` also go in here
- opening the file in my editor, shellcheck reports a number of quoting issues

I'd reccommend at least running shellcheck and the servo shell script linter once manually, and additionally hooking up `servo-tidy` to this repo in CI. (Adding shellcheck into `servo-tidy` is tracked at https://github.com/servo/servo/issues/19898.)

cc @asajeffrey

### PR DESCRIPTION
**Pull request by asajeffrey**
Fixes #4.

### CODE REVIEW

File: run-warc-tests.sh [hunk 1]
```diff
@@ -32,27 +38,27 @@ isTopLevel"
...
     echo "Testing ${URL} from archive ${ARCHIVE}"
-    wayback --proxy ${ARCHIVE} --port ${PORT} > /dev/null 2>&1 &
+    wayback --proxy "${ARCHIVE}" --port "${PORT}" > /dev/null 2>&1 &
 
     # Wait for the server to start up
     while ! PID=$(lsof -Pi :${PORT} -t); do sleep 1; done
 
     # Run a proxified servo on the URL, and save any WARC lines in the output file
-    timeout 2m proxychains ${SERVO} ${URL} | grep WARC | sed -e "s/WARC/${ARCHIVE}/" >> ${OUTPUT}
+    timeout 2m proxychains "${SERVO}" "${URL}" | grep WARC | sed -e "s/WARC/${ARCHIVE}/" >> "${OUTPUT}"
```
Comment (aneeshusa) [inline run-warc-tests.sh]: `$SERVO` is currently a single, whitespace separated string, so quoting it will break this execution. I'd recommend turning the SERVO variable into an array, and expanding it here with `"${SERVO[@]}"`. Might also be nice to rename it to `SERVO_CMD` (I originally thought it was the path to servo itself).

**Comment by aneeshusa** [comment]
I was going to add the `S-needs-code-changes` label, but it seems I don't have permissions on this repo (nor is Homu set up).

File: run-warc-tests.sh (hunk 1 above)
Comment (asajeffrey) [reply run-warc-tests.sh]: Done.

**Comment by asajeffrey** [comment]
IRC chat about enabling write access to this repo: https://mozilla.logbot.info/servo/20180130#c14214415

**Comment by asajeffrey** [comment]
Rebased.

**Comment by asajeffrey** [comment]
@aneeshusa?

File: run-warc-tests.sh [hunk 2]
```diff
@@ -4,18 +4,24 @@
...
-SERVO_DIR=$(readlink -f ${SERVO_DIR:-../servo})
-SERVO="${SERVO_DIR}/mach run -r -z \
-  --userscripts ${ARCHIVE_DIR}/user-agent-js \
-  --certificate-path ${ARCHIVE_DIR}/proxy-certs/pywb-ca.pem \
-  --pref dom.testperf.enabled"
+SERVO_DIR=$(readlink -f "${SERVO_DIR:-../servo}")
+SERVO_CMD=("${SERVO_DIR}/mach" run -r -z
+  --userscripts "${SCRIPT_DIR}/user-agent-js" \
+  --certificate-path "${SCRIPT_DIR}/proxy-certs/pywb-ca.pem" \
+  --pref dom.testperf.enabled)
```
Comment (aneeshusa) [inline run-warc-tests.sh]: Backslashes are not needed for line continuation inside an array, please remove them.
A formatting nit: I like block formatting and quoting all array members, e.g.
```
SERVO_CMD=(
    "${SERVO_DIR}/mach" 'run' '-r' '-z'
    ...
    '--pref' 'dom.testperf.enabled'
)
```

**Comment by aneeshusa** [comment]
If you also add a `.travis.yml` to run linting, we can hook up Homu to this repo. Feel free to save for a follow-up.

File: run-warc-tests.sh (hunk 2 above)
Comment (asajeffrey) [reply run-warc-tests.sh]: Quoted the strings and removed the backslashes.

**Comment by aneeshusa** [comment]
r=me after squash. Thanks!

**Comment by asajeffrey** [comment]
Thanks!
